http:
  port: "8080"
  read_timeout_in_second: 5
  write_timeout_in_second: 120
  idle_timeout_in_second: 120
  shutdown_timeout_in_second: 5

logger:
  level: dev

middleware:
  request_log:
    skip_paths: ["/health", "/metrics"]
    log_query: true

sqlite:
  dsn: "brook.db"

badger:
  dir: "badger"
