example:
  http:
    port: "8080"
    read_timeout_in_second: 5
    write_timeout_in_second: 120
    idle_timeout_in_second: 120

logger:
  level: dev

middleware:
  request_log:
    skip_paths: []
    log_query: true
  real_ip:
    trusted_proxies: []
