http:
  port: "8080"
  read_timeout_in_second: 5
  write_timeout_in_second: 120
  idle_timeout_in_second: 120
  shutdown_timeout_in_second: 30

logger:
  level: prd

middleware:
  request_log:
    skip_paths: ["/health", "/metrics"]
    log_query: true
  real_ip:
    trusted_proxies: []

postgres:
  dsn: ""
  max_conns: 25
  min_conns: 5

arangodb:
  endpoints: ["http://arangodb:8529"]
